name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: linux_amd64
    steps:
      - name: Checkout
        uses: https://git.talmage.dev/system/actions-checkout@v1

      - name: Install Docker and GCloud CLI
        run: |
          apt-get update
          apt-get install -y docker.io
          apt-get install -y apt-transport-https ca-certificates gnupg curl
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          apt-get update
          apt-get install -y google-cloud-cli
      
      - name: Authenticate to GCloud
        env:
          GCLOUD_SERVICE_ACCOUNT_KEY: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GCLOUD_SERVICE_ACCOUNT_KEY" > /tmp/gcloud-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcloud-key.json

      - name: Configure Docker for Artifact Registry
        env:
          DOCKER_REGISTRY_DOMAIN: ${{ secrets.DOCKER_REGISTRY_DOMAIN }}
        run: |
          gcloud auth configure-docker "$DOCKER_REGISTRY_DOMAIN" --quiet

      - name: Calculate short SHA
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Build and push image
        env:
          DOCKER_REGISTRY_DOMAIN: ${{ secrets.DOCKER_REGISTRY_DOMAIN }}
          DOCKER_REGISTRY_PATH: ${{ secrets.DOCKER_REGISTRY_PATH }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
        run: |
          IMAGE_REF="${DOCKER_REGISTRY_DOMAIN}/${DOCKER_REGISTRY_PATH}/${DOCKER_IMAGE}"
          docker build -t "${IMAGE_REF}:sha-${SHA_SHORT}" -t "${IMAGE_REF}:latest" .
          docker push "${IMAGE_REF}:sha-${SHA_SHORT}"
          docker push "${IMAGE_REF}:latest"

      - name: Redeploy Cloud Run service
        env:
          DOCKER_REGISTRY_DOMAIN: ${{ secrets.DOCKER_REGISTRY_DOMAIN }}
          DOCKER_REGISTRY_PATH: ${{ secrets.DOCKER_REGISTRY_PATH }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
          CLOUD_RUN_SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
          CLOUD_RUN_REGION: ${{ secrets.CLOUD_RUN_REGION }}
          GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
        run: |
          IMAGE_REF="${DOCKER_REGISTRY_DOMAIN}/${DOCKER_REGISTRY_PATH}/${DOCKER_IMAGE}"
          gcloud run deploy "$CLOUD_RUN_SERVICE" \
            --image "${IMAGE_REF}:latest" \
            --region "$CLOUD_RUN_REGION" \
            --project "$GCLOUD_PROJECT_ID" \
            --quiet

      - name: Cleanup gcloud service account key
        run: |
          rm -f /tmp/gcloud-key.json
