name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: linux_amd64
    steps:
      - name: Checkout
        uses: https://git.talmage.dev/system/actions-checkout@v1

      - name: Ensure Docker CLI
        run: |
          if command -v docker >/dev/null 2>&1; then
            docker --version
            exit 0
          fi
          if command -v sudo >/dev/null 2>&1; then
            SUDO="sudo"
          else
            SUDO=""
          fi
          if command -v apt-get >/dev/null 2>&1; then
            $SUDO apt-get update
            $SUDO apt-get install -y docker.io
          elif command -v apk >/dev/null 2>&1; then
            $SUDO apk add --no-cache docker-cli
          else
            echo "No supported package manager for Docker CLI." >&2
            exit 1
          fi

      - name: Calculate short SHA
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Login to registry
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and push image
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
        run: |
          IMAGE_REF="${DOCKER_REGISTRY}/${DOCKER_IMAGE}"
          docker build -t "${IMAGE_REF}:sha-${SHA_SHORT}" -t "${IMAGE_REF}:latest" .
          docker push "${IMAGE_REF}:sha-${SHA_SHORT}"
          docker push "${IMAGE_REF}:latest"
